[package]
name = "cargo-syu"
version = "0.1.0"
edition = "2021"
description = "cargo companion to keep packages up-to-date"
readme = "README.md"
repository = "https://github.com/idealseal/cargo-syu"
license = "MIT"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
git2 = "0.19.0"
home = "0.5.9"
owo-colors = "4.1.0"
rayon = "1.10.0"
reqwest = { version = "0.12.8", features = [ "default-tls", "blocking", "json", "http2"], default-features = false }
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tempfile = "3.13.0"
toml = "0.8.19"
