name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  lint:
    name: clippy

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: cargo clippy

  format:
    name: rustfmt

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt --all --check
